#!/usr/bin/env python3

import logging
import serial
import socket
import struct
import time

# === DEFINITIONS ===

def writeInt(value):
    ser.write(value.to_bytes(4,byteorder='little'))

    
# === MAIN SCRIPT ===

# Set up logging
logging.basicConfig(filename="uart.log",level=logging.INFO,filemode='w')


# Set up networking connection with robot
kuka_socket = socket.socket()
#host = socket.gethostname()
#host = "192.168.0.111"
host = "192.168.2.203"
port = 52323
kuka_socket.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
kuka_socket.bind((host,port))
kuka_socket.listen(5)

logging.info("Host : " + host)


# Set up serial connection to arduino
# Arduino will usually but not always be '/dev/ttyUSB0'

#for i in range(4):
#    try:
#        ser = serial.Serial('/dev/ttyUSB' + str(i),9600)
#    except Exception:
#        pass

# Serial over hardware pins
ser = serial.Serial('/dev/serial0',9600)
    
# Loop waiting for data from socket connection
# May need a way to fail out of this eventually

while (True):
    c, addr = kuka_socket.accept()
    value = c.recv(16)
    #intValue = struct.unpack('<i',value)
    #floatValue = struct.unpack('<f',value)
    logging.info("bytes: " + str(value[12:16]))
    #logging.info("int: " + str(intValue))
    #logging.info("float: " + str(floatValue))
    ser.write(value[12:16])

    
