#!/usr/bin/env python3

import serial
import struct
import time


ser = serial.Serial('/dev/ttyUSB0',9600)

def writeToArduino(value):
    ser.write(struct.pack('>B',value))
    

while (True):
    writeToArduino(0)
    time.sleep(1)
    writeToArduino(1)
    time.sleep(0.5)
