#!/usr/bin/env python3

import logging
import os
import serial
import select
import socket
import struct
import sys
import time

from tool_util import *

# === MAIN SCRIPT ===

setup_logging("uart")

socket = setup_server()


# Set up serial connection to arduino
# Arduino will usually but not always be '/dev/ttyUSB0'
ser = connect_serial()

# Loop waiting for data from socket connection
# May need a way to fail out of this eventually

while (True):
    c, addr = socket.accept()
    logging.info("Client : " + str(addr))
    while c is not -1 :
        value = c.recv(5)
        if not value or value[0] == 16:
            logging.info("End")
            break
        logging.info(value)
        if (ser):
            ser.write(value)
            while (ser.inWaiting() > 0):
                logging.info("Unknown Command: " + str(ser.read(1)))
    print("Connection closed")

