#!/usr/bin/env python3

import RPi.GPIO as GPIO

# define pins

pin_ribbon_3 = 14
pin_ribbon_4 = 15
pin_ribbon_5 = 18
pin_ribbon_6 = 17
pin_ribbon_7 = 4
pin_ribbon_8 = 3
pin_ribbon_9 = 2

# setup pins

GPIO.setmode(GPIO.BCM)
GPIO.setup(pin_ribbon_3, GPIO.OUT)
GPIO.setup(pin_ribbon_4, GPIO.OUT)
GPIO.setup(pin_ribbon_5, GPIO.OUT)
GPIO.setup(pin_ribbon_6, GPIO.OUT)
GPIO.setup(pin_ribbon_7, GPIO.OUT)
GPIO.setup(pin_ribbon_8, GPIO.OUT)
GPIO.setup(pin_ribbon_9, GPIO.OUT)


while(true):
    #this will be the network loop
    
