#!/usr/bin/env python3

""" Sets up a basic socket client to test network communication without using the robot. """

import socket

#host = "192.168.2.202"
host = "192.168.0.106"
port = 52323

s = socket.socket()
s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)

def write_int(value):
    s.connect((host,port))
    s.send((value).to_bytes(4,byteorder="little"))




