#!/usr/bin/env python3

""" Sets up a basic socket client to test network communication without using the robot. """

import socket

host = "192.168.2.203"
#host = "192.168.0.111"
port = 52323

def write_int(value):
    s = socket.socket()
    s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
    s.connect((host,port))
    s.send((value).to_bytes(4,byteorder="little"))
    s.close()

def write_bytes(values):
    s = socket.socket()
    s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
    s.connect((host,port))
    s.send(bytes(values))
    s.close()
